# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 14:25
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=300, unique=True)),
                ('ticker_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'ordering': ['ticker'],
            },
        ),
        migrations.AlterIndexTogether(
            name='ticker',
            index_together=set([('ticker', 'updated_date')]),
        ),
    ]
